/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class model_RsyncModel */

#ifndef _Included_model_RsyncModel
#define _Included_model_RsyncModel
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     model_RsyncModel
 * Method:    genSignature
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_model_RsyncModel_genSignature
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     model_RsyncModel
 * Method:    genDelta
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_model_RsyncModel_genDelta
  (JNIEnv *, jclass, jstring, jstring, jstring);

/*
 * Class:     model_RsyncModel
 * Method:    patch
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_model_RsyncModel_patch
  (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
